### ISSUE TITLE
Tag egg logs with a new Eggs category

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_eggs#1]
Provide a new "Eggs" log category, and automatically apply it to logs created via the /farm/eggs form. This will allow easier filtering to view all egg logs.

Also include an update hook that attempts to categorize existing logs based on the naming pattern used by the module.

**Comment by itsmerainier** [comment]
cannot enabled farm eggs it says Farm_quick (missing)

**Comment by mstenta** [comment]
Checkout the 7.x-1.0-beta2 tag - that is compatible with farmOS 7.x-1.0-beta16.

The new version of farmOS comes with a new farm_quick module, and the farm_eggs module uses that instead (in the 7.x-1.x branch, which is the latest).

**Comment by itsmerainier** [comment]
I've got an error...   

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'a.archived' in 'where clause': SELECT a.id FROM {farm_asset_property} p LEFT JOIN {farm_asset} a ON p.id = a.id WHERE p.name = 'farm_eggs' AND a.archived IS NULL; Array ( ) in farm_eggs_form() (line 52 of /var/www/farm/sites/all/modules/farm_eggs-7.x-1.0-beta2/farm_eggs.module).

**Comment by mstenta** [comment]
@itsmerainier - Ah oops - you're right.  Actually you should use tag 7.x-1.0-beta1 of the farm_eggs module.

Once the new version of farmOS is released (will be 7.x-1.0-beta17) then you can upgrade to the latest version of farm_eggs.

Hope that helps!  If you have further issues, please open a new issue here: https://github.com/farmOS/farm_eggs/issues/new (so we can keep this one specific to the feature request: "Tag egg logs with a new Eggs category"). Thanks!
