### ISSUE TITLE
Why this module is not published at drupal.org modules page?

### ISSUE THREAD

**Issue by calbasi** [farmOS/farm_eggs#4]
Is there any reason?

**Comment by mstenta** [comment]
In general I stopped mirroring all the farmOS contrib modules on drupal.org because it's just too much to maintain. Some of the older ones like Bees and Mushrooms are still there from the beginning.

I guess there is a benefit to having them on drupal.org to get update notifications, though, huh? Is that what you were wondering too?

**Comment by calbasi** [comment]
Well, installation process of stable versions is easy: drush en farm_eggs and the new versions, security updates included, are too a solid argument to have modules on drupal.org. It's the same than using debian packages from deb repos, instead of just use gitlab projects.

I think security is a must.

A minor reason could be increase the visibility of the project.

**Comment by mstenta** [comment]
All good points!

One other future consideration is: farmOS Field Kit + [Field Modules](https://github.com/farmOS/farmOS-client/issues/217). These are going to be JS apps that are packaged into farmOS/Drupal modules. However, they will require a separate Webpack-based build step, which is not something that Drupal.org currently provides. So our current thought is to use Github Actions for Field Module release packaging. The hope is that more and more farmOS modules will start to provide Field Modules (to add Field Kit integrations) - and if Drupal.org can't properly package those, then it means a whole swath of modules that can't be hosted on Drupal.org. So some things to figure out there...

**Comment by mstenta** [comment]
(It might make sense to move this issue to the farmOS issue queue, since it generally applies to all farmOS modules.)

**Comment by mstenta** [comment]
Another consideration (and reason to publish on drupal.org) is: translations.

There has been some good work going into translations of farmOS core, and we have been having similar discussions around translations for Field Modules as well. The hope is that we can leverage https://localize.drupal.org to host translations for both. But... in order for that to work, the code needs to be hosted on drupal.org.

That's just to say: we should at least *mirror* farmOS module repositories on drupal.org, but packaging could still be done on GitHub for the Field Modules.

**Comment by mstenta** [comment]
Done! https://www.drupal.org/project/farm_eggs

https://www.drupal.org/project/farm_eggs

**Comment by mstenta** [comment]
I will be closing the issue queue in this GitHub issue queue and making [drupal.org](https://www.drupal.org/project/issues/farm_eggs?categories=All) the new canonical queue.
